### ISSUE TITLE
No such file or directory logs

### ISSUE THREAD

**Issue by TheCarelessWhisper** [joaquinlpereyra/twitterImgBot#21]
so i keep running into this issue, i'm using bash on windows to execute, and i just can't seem to get it to launch without that error. 
root@DESKTOP-R7HT1HJ:/mnt/c/Users/name/Desktop/twitterImgBot-master# python twitterbot.py
Traceback (most recent call last):
  File "twitterbot.py", line 209, in <module>
    main()
  File "twitterbot.py", line 197, in main
    post_number = get_post_number(manual_post_number)
  File "twitterbot.py", line 145, in get_post_number
    return get_post_number_from_log(config.log_file)
  File "twitterbot.py", line 131, in get_post_number_from_log
    post_number = open(log_file, 'r').readlines()[-1]
IOError: [Errno 2] No such file or directory: u'C:/Users/name/Desktop/twitterImgBot-master/logs/'
root@DESKTOP-R7HT1HJ:/mnt/c/Users/name/Desktop/twitterImgBot-master# python test/twitterbot_tests.py
python: can't open file 'test/twitterbot_tests.py': [Errno 2] No such file or directory
root@DESKTOP-R7HT1HJ:/mnt/c/Users/name/Desktop/twitterImgBot-master# python test/twitterbot_tests.py
python: can't open file 'test/twitterbot_tests.py': [Errno 2] No such file or directory
root@DESKTOP-R7HT1HJ:/mnt/c/Users/name/Desktop/twitterImgBot-master# python test/twitterbot_tests.py
python: can't open file 'test/twitterbot_tests.py': [Errno 2] No such file or directory
if someone could point me to what i'm doing wrong? i've tried all kinds of configurations at this point

**Comment by joaquinlpereyra** [comment]
Hi :). I haven't looked at this project for a while now and a number of things could be going foul, but have you copied the entire project structure?

Do yo have this folder `] No such file or directory: u'C:/Users/name/Desktop/twitterImgBot-master/logs/'` in your system? it is in the repository.
