### ISSUE TITLE
ValueError: invalid literal for int() with base 10: ''

### ISSUE THREAD

**Issue by GreatScherzo** [joaquinlpereyra/twitterImgBot#26]
Exception seems to happen when executing the program in config.py

```
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1035, in _handle_fromlist
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Barzarin\PycharmProjects\twitterImgBot-master\twitterImgBot-master\settings\config.py", line 23, in <module>
    tolerance = int(app_config['allow_repeat_after'])
ValueError: invalid literal for int() with base 10: ''
```

Other info:
Python version: Python 3.7.1

**Comment by GreatScherzo** [comment]
Probably happen because I didn't fill in the configs yet lol
