### ISSUE TITLE
Use filename or file properties in tweet text?

### ISSUE THREAD

**Issue by MrCarter13** [joaquinlpereyra/twitterImgBot#8]
Somehow be able to include a filename in the tweet text, which would allow for sourcing images directly in the tweet.

**Comment by joaquinlpereyra** [comment]
Ok, very quick and dirty: 

Replace line 11 of bot/status.py with:

`self.text = tweet_media.split('/')[-1]`

That should be enough. Mind that this works for Linux and (I think) Mac, I think Windows uses \ to separate folders, so you should replace the '/' with '\' for Windows, I think. 

Also, this also tweets the file extension. If you don't want to do that, you could do something like

`self.text = tweet_media.split('/')[-1].split('.')[0]`

But I didn't test that.

I'll leave this open to include it in the options and such in the future.

**Comment by MrCarter13** [comment]
awesome, ill try it out, thanks!

**Comment by joaquinlpereyra** [comment]
@MrCarter13 let me know if it worked! thanks for the contribution :)

**Comment by MrCarter13** [comment]
Sorry for the delayed update, busy week.  I updated line 11 of bot/status.py and it errors out with this output:

Traceback (most recent call last):
  File "twitterbot.py", line 4, in <module>
    from bot import status
  File "/home/pi/twitterbot/twitterImgBot-master/bot/status.py", line 9, in <module>
    class Tweet():
  File "/home/pi/twitterbot/twitterImgBot-master/bot/status.py", line 11, in Tweet
    self.text = tweet_media.split('/')[-1]
NameError: name 'tweet_media' is not defined

**Comment by MrCarter13** [comment]
okay i tried out your solution and it sort of works,  the image is still tweeted properly, but the filename seems to be randomly chosen independently of the image.  For example if the bot tweets ImageA.jpg the filename included in the tweet text might be ImageB.jpg

Another quick question: how would i go about including a url before the filename?

thanks for your feedback :)

**Comment by joaquinlpereyra** [comment]
uh. that's weird. i'll look into it. 

if you want to include the same url in every one of your posts, look at the "tweet text" option. if you want the url to change depending on the image, that's... not possible right now, unless not in a non-hackish way.
